
CREATE TABLE CADASTRAR_USUARIOS(
ID INT(11) NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
CIDADE VARCHAR(50) NOT NULL,
ESTADO VARCHAR(20) NOT NULL,
CEP VARCHAR(30) NOT NULL,
NUMERO CHAR(15) NOT NULL,
IDADE CHAR(3) NOT NULL,
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY (ID)
);